export const defaultBPM = 120;
export const fingers = ["p", "i", "m", "a"];
export const strings = [6, 5, 4, 3, 2, 1];

export const part = [
  { note: "E3", finger: "p", string: 6 },
  { note: "E4", finger: "i", string: 4 },
  { note: "B3", finger: "p", string: 5 },
  { note: "G4", finger: "i", string: 3 },
  { note: "E4", finger: "p", string: 4 },
  { note: "B4", finger: "m", string: 2 },
  { note: "G4", finger: "i", string: 3 },
  { note: "E5", finger: "a", string: 1 },
  { note: "B4", finger: "m", string: 2 },
  { note: "E5", finger: "a", string: 1 },
  { note: "G4", finger: "i", string: 3 },
  { note: "B4", finger: "m", string: 2 },
  { note: "E4", finger: "p", string: 4 },
  { note: "G4", finger: "i", string: 3 },
  { note: "B3", finger: "p", string: 5 },
  { note: "E4", finger: "i", string: 4 },
  { note: "E3", finger: "p", string: 6 },
  { note: "F#4", finger: "i", string: 4 },
  { note: "C4", finger: "p", string: 5 },
  { note: "A4", finger: "i", string: 3 },
  { note: "F#4", finger: "p", string: 4 },
  { note: "C5", finger: "m", string: 2 },
  { note: "A4", finger: "i", string: 3 },
  { note: "E5", finger: "a", string: 1 },
  { note: "C5", finger: "m", string: 2 },
  { note: "E5", finger: "a", string: 1 },
  { note: "A4", finger: "i", string: 3 },
  { note: "C5", finger: "m", string: 2 },
  { note: "F#4", finger: "p", string: 4 },
  { note: "A4", finger: "i", string: 3 },
  { note: "C4", finger: "p", string: 5 },
  { note: "F#4", finger: "i", string: 4 },
];
